export const refs = {
    btnOpenMeny: document.querySelector('.menu'),
    optnBtn: document.querySelector('.hero-btn-js'),
    backdrop: document.querySelector('.backdrop-hero'),
    closeBtn: document.querySelector('.close-js'),
    hoverlaOpen: document.querySelector('.open-hoverla-js'),
    bukovelOpen: document.querySelector('.open-bukovel-js'),
    carpatiansOpen: document.querySelector('.open-carpatian-js'),
    upcomingClose: document.querySelector('.upcoming-btn-close-js'),
    backdropUpcoming: document.querySelector('.upcoming-backdrop'),
    heroDescr: document.querySelector('.hero__description'),
    heroTitle: document.querySelector('.hero__title'),
    mobileMeny: document.querySelector('.mobile-menu'),
    disabledBtn: document.querySelector('.primari-btn'),
    logo: document.querySelector('.logo'),
    btnMenu: document.querySelector('.menu-js'),
};